data_preprocessing:
  test_size: 0.2
  random_state: 42

feature_params:
  target: "posttest"
  numeric_features: ["pretest"]
  categorical_features: ["school_setting", "school_type", "teaching_method", "gender", "lunch"]

linear_regression:
  fit_intercept: true

  random_state: 42

decision_tree:
  max_depth: 5
  min_samples_split: 2

catboost:
  iterations: 1000
  learning_rate: 0.03
  random_seed: 42

xgboost:
  max_depth: 6
  learning_rate: 0.1

mlp:
  hidden_layer_sizes: [100, 50]
  activation: relu

evaluation:
  metrics: [mse, rmse, r2]